//! WASM plugin side — compiled to wasm32-unknown-unknown for distribution,
//! OR as a native cdylib for the C ABI benchmark.
//!
//! Memory contract with the host:
//!   alloc_buffer(len)              -> ptr   allocate `len` bytes
//!   dealloc_buffer(ptr, len)       -> ()    free a previous alloc
//!   extract(in_ptr, in_len, type_id) -> u64 packed (out_ptr | out_len<<32)
//!   table_count()                  -> u32   number of known tables
//!   table_name(idx)                -> u64   packed ptr/len for table name

// ── cfg: no_std only on wasm32 ───────────────────────────────────────────────
#![cfg_attr(target_arch = "wasm32", no_std)]

// On wasm32 we need alloc explicitly; on native std covers it.
#[cfg(target_arch = "wasm32")]
extern crate alloc;

// On wasm32 pull in alloc types; on native they come from std.
#[cfg(target_arch = "wasm32")]
use alloc::{format, string::String, vec::Vec};
#[cfg(not(target_arch = "wasm32"))]
use std::{format, string::String, vec::Vec};

use core::alloc::Layout;

// ── wasm32-only: allocator + panic handler ───────────────────────────────────

#[cfg(target_arch = "wasm32")]
mod wasm_support {
    // wasm32-unknown-unknown has no default allocator.
    // dlmalloc provides one; add to plugin/Cargo.toml:
    //   dlmalloc = { version = "0.2", features = ["global"] }
    use dlmalloc::GlobalDlmalloc;

    #[global_allocator]
    static ALLOC: GlobalDlmalloc = GlobalDlmalloc;

    #[panic_handler]
    fn panic(_: &core::panic::PanicInfo) -> ! {
        // wasm32 trap instruction — terminates the WASM instance cleanly.
        core::arch::wasm32::unreachable()
    }
}

// ── host memory API ──────────────────────────────────────────────────────────

#[cfg(target_arch = "wasm32")]
use alloc::alloc::{alloc, dealloc};
#[cfg(not(target_arch = "wasm32"))]
use std::alloc::{alloc, dealloc};

#[unsafe(no_mangle)]
pub extern "C" fn alloc_buffer(size: usize) -> *mut u8 {
    let layout = Layout::from_size_align(size.max(1), 8).unwrap();
    unsafe { alloc(layout) }
}

#[unsafe(no_mangle)]
pub extern "C" fn dealloc_buffer(ptr: *mut u8, size: usize) {
    if ptr.is_null() { return; }
    let layout = Layout::from_size_align(size.max(1), 8).unwrap();
    unsafe { dealloc(ptr, layout) };
}

// ── stub table (replace with flatc-generated code) ───────────────────────────

mod tables {
    //! In a real project this is auto-generated by build.rs from flatc output.
    //! One entry per .fbs table:
    //!   flatc --rust --gen-object-api --rust-serialize schema.fbs

    #[cfg(target_arch = "wasm32")]
    use alloc::{string::String, vec::Vec};
    #[cfg(not(target_arch = "wasm32"))]
    use std::{string::String, vec::Vec};

    use serde::Serialize;

    #[derive(Serialize)]
    pub struct StubTableT {
        pub id:     i64,
        pub name:   String,
        pub values: Vec<f32>,
    }

    /// Mirrors what flatc --gen-object-api emits: root_as_X + .unpack().
    pub fn root_as_stub(buf: &[u8]) -> Result<StubTableT, &'static str> {
        if buf.len() < 100 { return Err("buffer too small"); }
        let id = i64::from_le_bytes(buf[0..8].try_into().unwrap());
        let mut values = Vec::with_capacity(5);
        for i in 0..5usize {
            let off = 80 + i * 4;
            values.push(f32::from_le_bytes(buf[off..off+4].try_into().unwrap()));
        }
        Ok(StubTableT { id, name: String::from("Aru"), values })
    }
}

// ── dispatch table ───────────────────────────────────────────────────────────

struct TableEntry {
    name:    &'static str,
    extract: fn(&[u8]) -> Result<Vec<u8>, &'static str>,
}

static DISPATCH_TABLE: &[TableEntry] = &[
    TableEntry {
        name: "StubTable",
        extract: |buf| {
            tables::root_as_stub(buf)
                .and_then(|t| serde_json::to_vec(&t).map_err(|_| "json error"))
        },
    },
    // Add generated entries here, or via build.rs:
    // TableEntry { name: "CharacterExcelTable", extract: |buf| { ... } },
];

#[unsafe(no_mangle)]
pub extern "C" fn table_count() -> u32 {
    DISPATCH_TABLE.len() as u32
}

/// Returns packed (ptr | len<<32) for the name of table `idx`, or 0 if OOB.
#[unsafe(no_mangle)]
pub extern "C" fn table_name(idx: u32) -> u64 {
    let Some(entry) = DISPATCH_TABLE.get(idx as usize) else { return 0 };
    let bytes = entry.name.as_bytes();
    let ptr   = alloc_buffer(bytes.len());
    unsafe { core::ptr::copy_nonoverlapping(bytes.as_ptr(), ptr, bytes.len()) };
    pack(ptr, bytes.len())
}

// ── extract ───────────────────────────────────────────────────────────────────

#[unsafe(no_mangle)]
pub extern "C" fn extract(in_ptr: *const u8, in_len: usize, type_id: u32) -> u64 {
    let input = unsafe { core::slice::from_raw_parts(in_ptr, in_len) };

    let Some(entry) = DISPATCH_TABLE.get(type_id as usize) else { return 0 };

    let json_bytes = match (entry.extract)(input) {
        Ok(b)  => b,
        Err(e) => format!(r#"{{"error":{e:?}}}"#).into_bytes(),
    };

    let out_len = json_bytes.len();
    let out_ptr = alloc_buffer(out_len);
    unsafe { core::ptr::copy_nonoverlapping(json_bytes.as_ptr(), out_ptr, out_len) };
    pack(out_ptr, out_len)
}

#[inline(always)]
fn pack(ptr: *mut u8, len: usize) -> u64 {
    (ptr as u64) | ((len as u64) << 32)
}
