//! WASM plugin side — compiled to wasm32-unknown-unknown.
//!
//! This crate is what you regenerate every game update:
//!   1. Run flatc to regenerate table.rs
//!   2. cargo build --release --target wasm32-unknown-unknown -p plugin
//!   3. Ship the resulting .wasm — the host extractor binary never changes.
//!
//! Memory contract with the host:
//!   alloc_buffer(len)        -> ptr          allocate `len` bytes, return ptr
//!   dealloc_buffer(ptr, len) -> ()           free a previous alloc
//!   extract(in_ptr, in_len, type_id) -> u64  packed (out_ptr | out_len<<32)
//!
//!   type_id is a u32 that maps to a specific FlatBuffer table.
//!   The host learns the mapping from the manifest embedded in the .wasm
//!   via the `table_count` and `table_name` exports.

#![no_std]
extern crate alloc;

use alloc::{
    alloc::{GlobalAlloc, Layout},
    format,
    string::String,
    vec::Vec,
};

// ── allocator ────────────────────────────────────────────────────────────────
// wasm32-unknown-unknown has no default allocator; wire up dlmalloc.

#[cfg(not(test))]
mod allocator {
    use core::alloc::{GlobalAlloc, Layout};

    struct WasmAlloc;

    // dlmalloc is the de-facto allocator for wasm32-unknown-unknown no_std crates.
    // Add `dlmalloc = { version = "0.2", features = ["global"] }` to Cargo.toml
    // and the linker will wire it up; the stubs below just forward to it.
    unsafe impl GlobalAlloc for WasmAlloc {
        unsafe fn alloc(&self, layout: Layout) -> *mut u8 {
            unsafe { dlmalloc::GlobalDlmalloc.alloc(layout) }
        }
        unsafe fn dealloc(&self, ptr: *mut u8, layout: Layout) {
            unsafe { dlmalloc::GlobalDlmalloc.dealloc(ptr, layout) }
        }
    }

    #[global_allocator]
    static A: WasmAlloc = WasmAlloc;
}

#[cfg(not(test))]
#[panic_handler]
fn panic(_: &core::panic::PanicInfo) -> ! {
    core::arch::wasm32::unreachable()
}

// ── host memory API ──────────────────────────────────────────────────────────

#[unsafe(no_mangle)]
pub extern "C" fn alloc_buffer(size: usize) -> *mut u8 {
    let layout = Layout::from_size_align(size.max(1), 8).unwrap();
    unsafe { alloc::alloc::alloc(layout) }
}

#[unsafe(no_mangle)]
pub extern "C" fn dealloc_buffer(ptr: *mut u8, size: usize) {
    if ptr.is_null() { return; }
    let layout = Layout::from_size_align(size.max(1), 8).unwrap();
    unsafe { alloc::alloc::dealloc(ptr, layout) }
}

// ── table registry ───────────────────────────────────────────────────────────
// Generated by flatc / build.rs in a real project. Shown here with a stub
// table so the structure is clear.

mod tables {
    // In a real project this module is auto-generated by build.rs scanning
    // flatc output. It re-exports the root_as_* fns and *T owned structs.
    //
    // Example (flatc --rust --gen-object-api --rust-serialize):
    //
    //   pub mod character_excel;
    //   pub mod item_excel;
    //   ...
    //   pub use character_excel::*;
    //   pub use item_excel::*;

    /// A stub "table" used for the benchmark — simulates what flatc emits.
    /// Replace this with `include!(concat!(env!("OUT_DIR"), "/tables.rs"))`.
    pub mod stub {
        use alloc::{string::String, vec::Vec};
        use serde::Serialize;

        #[derive(Serialize)]
        pub struct StubTableT {
            pub id:     i64,
            pub name:   String,
            pub values: Vec<f32>,
        }

        pub fn root_as_stub(buf: &[u8]) -> Result<StubTableT, &'static str> {
            // Real impl would be:
            //   flatbuffers::root::<StubTable>(buf)
            //       .map_err(|_| "invalid flatbuffer")
            //       .map(|t| t.unpack())
            //
            // For the benchmark we just decode our hand-crafted payload.
            if buf.len() < 100 { return Err("buffer too small"); }
            let id = i64::from_le_bytes(buf[0..8].try_into().unwrap());
            let mut values = Vec::with_capacity(5);
            for i in 0..5usize {
                let off = 80 + i * 4;
                values.push(f32::from_le_bytes(buf[off..off+4].try_into().unwrap()));
            }
            Ok(StubTableT { id, name: String::from("Aru"), values })
        }
    }
}

// ── dispatch table ───────────────────────────────────────────────────────────

/// Number of tables this plugin knows about.
/// Exported so the host can enumerate them without hardcoding.
#[unsafe(no_mangle)]
pub extern "C" fn table_count() -> u32 {
    DISPATCH_TABLE.len() as u32
}

struct TableEntry {
    name:    &'static str,
    extract: fn(&[u8]) -> Result<Vec<u8>, &'static str>,
}

static DISPATCH_TABLE: &[TableEntry] = &[
    TableEntry {
        name: "StubTable",
        extract: |buf| {
            tables::stub::root_as_stub(buf)
                .and_then(|t| serde_json::to_vec(&t).map_err(|_| "json error"))
        },
    },
    // In a real project, build.rs generates one entry per flatc-emitted table:
    // TableEntry { name: "CharacterExcelTable", extract: |buf| { ... } },
    // TableEntry { name: "ItemExcelTable",      extract: |buf| { ... } },
];

/// Write the name of table `idx` into a newly allocated buffer.
/// Returns packed (ptr | len<<32), or 0 if idx is out of range.
#[unsafe(no_mangle)]
pub extern "C" fn table_name(idx: u32) -> u64 {
    let Some(entry) = DISPATCH_TABLE.get(idx as usize) else { return 0 };
    let bytes = entry.name.as_bytes();
    let ptr   = alloc_buffer(bytes.len());
    unsafe { core::ptr::copy_nonoverlapping(bytes.as_ptr(), ptr, bytes.len()) };
    pack(ptr, bytes.len())
}

// ── main extract entry point ─────────────────────────────────────────────────

/// Deserialize `in_len` bytes at `in_ptr` as table `type_id` and return JSON.
/// Returns packed (out_ptr | out_len<<32).
/// Returns 0 on unknown type_id.
/// On parse/serialization error returns a JSON `{"error":"..."}` payload.
#[unsafe(no_mangle)]
pub extern "C" fn extract(in_ptr: *const u8, in_len: usize, type_id: u32) -> u64 {
    let input = unsafe { core::slice::from_raw_parts(in_ptr, in_len) };

    let Some(entry) = DISPATCH_TABLE.get(type_id as usize) else { return 0 };

    let json_bytes = match (entry.extract)(input) {
        Ok(b)  => b,
        Err(e) => format!(r#"{{"error":{:?}}}"#, e).into_bytes(),
    };

    let out_len = json_bytes.len();
    let out_ptr = alloc_buffer(out_len);
    unsafe { core::ptr::copy_nonoverlapping(json_bytes.as_ptr(), out_ptr, out_len) };
    pack(out_ptr, out_len)
}

#[inline(always)]
fn pack(ptr: *mut u8, len: usize) -> u64 {
    (ptr as u64) | ((len as u64) << 32)
}
